### PR TITLE
Ingest Martian Fork

### LINKED ISSUE #330: martian: rewrite CI in GH action
Travis stopped running tests on our fork, we need to port the CI to GH actions.

### PR DESCRIPTION
**Pull request by mmatczuk**
Ingest our fork github.com/saucelabs/martian/v3 as internal/martian

The code is based on https://github.com/saucelabs/martian/commit/1aab6935a07cb1588ce8b74312f3475bfe2f0ffa.

The commits were obtained by running the following commands:

```
git clone git@github.com:saucelabs/forwarder.git F
git clone git@github.com:saucelabs/martian.git M
cd M
git filter-repo --force --path-regex '^[A-Za-z_]+\.go|fifo' --path-rename :internal/martian/ --path-rename fifo:internal/martian/fifo --message-callback '
msg = message.decode("utf-8").strip()
modified_msg = "martian: " + msg[0].lower() + msg[1:]
return modified_msg.encode("utf-8")'
git remote add F ../F
git fetch F
git rebase F/main
```

Then all the commits present in the original martian repo were squashed into a single commit.

This was not enough and I needed to port additional required modules because of the dependency on martian.Context.

Note that the Martian modules may or may not work depending if they are using the context. 

Fixes #330

### CODE REVIEW

**Comment by Choraden** [comment]
Please squash eacf3c60 with e9d9f1ce.

**Comment by Choraden** [comment]
How about we squash 136396b9 with the 215007f9?

**Comment by Choraden** [comment]
Well done @mmatczuk!
LGTM

**Comment by mmatczuk** [comment]
> How about we squash https://github.com/saucelabs/forwarder/commit/136396b9aee027a8b429012c7b51aa6aa3b89ae4 with the https://github.com/saucelabs/forwarder/commit/215007f9cb63b36e96b9818fd340a3165e762764?

IMO it's different because we are not porting all the packages but selected few.

**Pull request merged**
