### PR TITLE
Improve packaging and rework local dev

### PR DESCRIPTION
**Pull request by Choraden**

### CODE REVIEW

**Comment by mmatczuk** [comment]
You added `packaging/forwarder.env` in packaging: remove NOFILE limit

**Comment by Choraden** [comment]
I added only a commented out `GOMEMLIMIT` example to balance the removal of NOFILE limit. Shouldn't it be there?

**Comment by mmatczuk** [comment]
It would be better to add that in two commits.

**Comment by mmatczuk** [comment]
Thanks.

**Pull request merged**
