### PR TITLE
Eager listener init

### PR DESCRIPTION
**Pull request by mmatczuk**

### CODE REVIEW

**Comment by Choraden** [comment]
I don't like that there is more the one subject which closes the listener i.e.`Proxy.Close` and `Proxy.Run`, but it's not wrong though, just my personal feeling.

**Comment by Choraden** [comment]
How about documenting that one needs to close the Proxy once created?

**Comment by mmatczuk** [comment]
> I don't like that there is more the one subject which closes the listener i.e.Proxy.Close and Proxy.Run, but it's not wrong though, just my personal feeling.

It's needed in case of martian so that it stop listening, it is indeed wrong.

**Comment by mmatczuk** [comment]
Added comments.

**Comment by Choraden** [comment]
I'm wondering if we could add `Proxy::close()` and call it in both `Proxy:Close()`, `Proxy:Run()` to indicate that they both do the same.

**Comment by mmatczuk** [comment]
Done.

**Pull request merged**
